server:
  port: 8002

spring:
  application:
    name: provider-payment
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1311664842

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka, http://localhost:9002/eureka
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
  instance:
    instance-id: provider-payment8002
    # 访问eureka主页时显示ip地址
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.codeliu.entity

